name: Python Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code with flake8
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト（uses: ステップには working-directory は不要）
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: .
      
      # Python 3.13 のセットアップ（uses: ステップには working-directory は不要）
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      
      # pip のアップグレード（run: ステップなので working-directory を指定）
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        working-directory: .
      
      # Poetry のインストール（run: ステップなので working-directory を指定）
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
        working-directory: .
      
      # 依存関係のインストール（run: ステップなので working-directory を指定）
      - name: Install dependencies with Poetry
        run: poetry install --no-root
        working-directory: .
      
      # flake8 の実行（run: ステップなので working-directory を指定）
      - name: Run flake8
        run: poetry run flake8 .
        working-directory: .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: .
      
      # Python 3.13 のセットアップ
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      
      # pip のアップグレード
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        working-directory: .
      
      # Poetry のインストール
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
        working-directory: .
      
      # 依存関係のインストール
      - name: Install dependencies with Poetry
        run: poetry install --no-root
        working-directory: .
      
      # ユニットテストの実行
      - name: Run Unit Tests
        run: poetry run python -m unittest discover tests
        working-directory: .
